name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
jobs:
  build-android-web:
    name: Build android & web
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
          cache-key: flutter
          cache-path: ${{ runner.tool_cache }}/flutter
      - run: flutter --version
      - name: Running flutter pub
        run: flutter pub get
      - name: Clean build
        run: flutter clean
      - name: Building for android apk & appbundle
        run: |
          flutter build apk
          flutter build appbundle
      # web
      - name: Clean build
        run: flutter clean
      - name: Building for web
        run: flutter build web
  build-ios:
    name: Build ios
    runs-on: macos-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
          cache-key: flutter
          cache-path: ${{ runner.tool_cache }}/flutter
      - name: Running flutter pub
        run: flutter pub get
      - name: Clean build
        run: flutter clean
      - name: Building for ios
        run: flutter build ios --release --no-codesign
